config/routes.rb
Rails.application.routes.draw do
  resources :registros
  devise_for :users
  get 'static_pages/index'

root 'static_pages#index'

end

app/models/registro.rb
class Registro < ActiveRecord::Base
  belongs_to :user

  def self.to_csv(options = {})
		CSV.generate(options) do |csv|
			csv << column_names
			all.each do |registro|
				csv << registro.attributes.values_at(*column_names)
			end
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :registros

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def logged_in?
    # "!!" converts the "current_user" variable to a boolean (exists or doesn't)
    !!current_user
  end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_registro, only: [:show, :edit, :update, :destroy]
 
  # GET /registros
  # GET /registros.json
  def index
    @registros = Registro.all  # paginate(page: params[:page], per_page: 5) # unless request.format == 'xls'
    
    respond_to do |format|
      format.html
      format.csv { send_data text: @registros.to_csv }
      # For excel exporting
      format.xls # { send_data @registros.to_csv(col_sep: "\t") }
    end
  end

  # GET /registros/1
  # GET /registros/1.json
  def show
  end

  # GET /registros/new
  def new
    @registro = Registro.new
  end

  # GET /registros/1/edit
  def edit
  end

  # POST /registros
  # POST /registros.json
  def create
    @registro = Registro.new(registro_params)
    @registro.user = current_user

    respond_to do |format|
      if @registro.save
        format.html { redirect_to @registro, notice: 'Registro was successfully created.' }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registros/1
  # PATCH/PUT /registros/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to @registro, notice: 'Registro was successfully updated.' }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registros/1
  # DELETE /registros/1.json
  def destroy
    @registro.destroy
    respond_to do |format|
      format.html { redirect_to registros_url, notice: 'Registro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_registro
      @registro = Registro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:nombre, :apellido, :puesto, :materia, :centro, :pueblo, :nivel, :sec, :email, :telefono, :comentario, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  	redirect_to registros_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SMARTSIGNUP" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- redirect_to registros_path if logged_in? -->
        
        <a class="navbar-brand" href="/"><span class="sm-brand">SM</span>ARTSIGNUP</a>

        <div class="navbar-collapse collapse navbar-responsive-collapse">
          
          <ul class="nav navbar-nav">
            <li><%= link_to "Registros", "/registros"  %></li>
            <!-- <li><%= link_to "Link2", "/path2"  %></li> -->
            <!-- <li><%= link_to "Link3", "/path3"  %></li> -->
          </ul>

          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="col-md-8 user-name">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
              </li>
              <li class="col-md-1"></li>
              <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path,
                  class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
              </li>
            <% end %>
           </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <!-- <footer>
        <p>&copy; Company 2017</p>
      </footer> -->

      <!-- <footer class="footer">
        <div class="container">
          <div class="text-center text-muted">
            <p>&copy;2017 Ediciones SM</p>
          </div>
        </div>
    </footer> -->

    </div> <!-- /container -->

  </body>
</html>

app/views/registros/_form.html.erb
<%= form_for @registro, :html => { :class => "form-horizontal registro" } do |f| %>

  <% if @registro.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@registro.errors.count, "error") %> prohibited this registro from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @registro.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nombre, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nombre, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nombre) %>
  </div>
  <div class="form-group">
    <%= f.label :apellido, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :apellido, :class => 'form-control' %>
    </div>
    <%=f.error_span(:apellido) %>
  </div>
  <!-- <div class="form-group">
    <%= f.label :puesto, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :puesto, :class => 'form-control' %>
    </div>
    <%=f.error_span(:puesto) %>
  </div> -->

  <!-- Static select menu in form -->
  <div class="form-group">
    <%= f.label "Puesto", class: 'control-label col-lg-2' %>
    <div class="controls col-lg-10">
      <%= f.select(:puesto, options_for_select([['DIRECTOR', 'DIRECTOR'], ['MAESTRO', 'MAESTRO'], ['COORDINADOR', 'COORDINADOR'], ['FACILITADOR', 'FACILITADOR'], ['OTRO', 'OTRO']]), { include_blank: true }) %>
    </div>
  </div><!-- End of static select menu -->

  <!-- <div class="form-group">
    <%= f.label :materia, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :materia, :class => 'form-control' %>
    </div>
    <%=f.error_span(:materia) %>
  </div> -->

  <div class="form-group">
    <%= f.label "Materia", class: 'control-label col-lg-2' %>
    <div class="controls col-lg-10">
      <%= f.select(:materia, options_for_select([['ESPAÑOL', 'ESPAÑOL'], ['INGLÉS', 'INGLÉS'], ['SOCIALES', 'SOCIALES'], ['MATEMÁTICAS', 'MATEMÁTICAS'], ['CIENCIAS', 'CIENCIAS'], ['RELIGIÓN', 'RELIGIÓN'], ['OTRA', 'OTRA']]), { include_blank: true }) %>
    </div>
  </div><!-- End of static select menu -->

  <div class="form-group">
    <%= f.label :centro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :centro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:centro) %>
  </div>
  <div class="form-group">
    <%= f.label :pueblo, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :pueblo, :class => 'form-control' %>
    </div>
    <%=f.error_span(:pueblo) %>
  </div>
  <!-- <div class="form-group">
    <%= f.label :nivel, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nivel, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nivel) %>
  </div> -->

  <div class="form-group">
    <%= f.label "Nivel", class: 'control-label col-lg-2' %>
    <div class="controls col-lg-10">
      <%= f.select(:nivel, options_for_select([['PREESCOLAR', 'PREESCOLAR'], ['ELEMENTAL', 'ELEMENTAL'], ['INTERMEDIA', 'INTERMEDIA'], ['SUPERIOR', 'SUPERIOR'], ['K', 'K'], ['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10'], ['11', '11'], ['12', '12']]), { include_blank: true }) %>
    </div>
  </div><!-- End of static select menu -->

  <!-- <div class="form-group">
    <%= f.label :sec, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :sec, :class => 'form-control' %>
    </div>
    <%=f.error_span(:sec) %>
  </div> -->

  <div class="form-group">
    <%= f.label "SEC", class: 'control-label col-lg-2' %>
    <div class="controls col-lg-10">
      <%= f.select(:sec, options_for_select([['SÍ', 'SÍ'], ['NO', 'NO']]), { include_blank: true }) %>
    </div>
  </div><!-- End of static select menu -->

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :telefono, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefono, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefono) %>
  </div>
  <div class="form-group">
    <%= f.label :comentario, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :comentario, :class => 'form-control' %>
    </div>
    <%=f.error_span(:comentario) %>
  </div>
  <!-- <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div> -->

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                registros_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/registros/edit.html.erb
<%- model_class = Registro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/registros/index.html.erb
<%- model_class = Registro -%>
<div class="container">
  <div class="page-header">
    <ul class="list-inline pull-right">
      <li><%= link_to t('.new', :default => t("helpers.links.new")),
            new_registro_path,
            :class => 'btn btn-primary' %></li>
      <li><%= link_to "Exportar a Excel", registros_path(format: "xls"), :class => 'btn btn-success' %></li>
    </ul>
    <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
  </div>
</div><!-- End of header container -->
<div class="container">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <!-- <th><%= model_class.human_attribute_name(:id) %></th> -->
        <th><%= model_class.human_attribute_name(:nombre) %></th>
        <th><%= model_class.human_attribute_name(:apellido) %></th>
        <!-- <th><%= model_class.human_attribute_name(:puesto) %></th> -->
        <th><%= model_class.human_attribute_name(:materia) %></th>
        <th><%= model_class.human_attribute_name(:centro) %></th>
        <th><%= model_class.human_attribute_name(:pueblo) %></th>
        <th><%= model_class.human_attribute_name(:nivel) %></th>
        <!-- <th><%= model_class.human_attribute_name(:sec) %></th> -->
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:telefono) %></th>
        <!-- <th><%= model_class.human_attribute_name(:comentario) %></th> -->
        <!-- <th><%= model_class.human_attribute_name(:user_id) %></th> -->
        <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @registros.each do |registro| %>
        <tr>
          <!-- <td><%= link_to registro.id, registro_path(registro) %></td> -->
          <td><%= link_to registro.nombre, registro_path(registro) %></td>
          <td><%= registro.apellido %></td>
          <!-- <td><%= registro.puesto %></td> -->
          <td><%= registro.materia %></td>
          <td><%= registro.centro %></td>
          <td><%= registro.pueblo %></td>
          <td><%= registro.nivel %></td>
          <!-- <td><%= registro.sec %></td> -->
          <td><%= registro.email %></td>
          <td><%= registro.telefono %></td>
          <!-- <td><%= truncate(registro.comentario, :length => 15) %></td> -->
          <!-- <td><%= registro.user_id %></td> -->
          <!-- <td><%=l registro.created_at %></td> -->
          <td>
            <div class="btn-secondary"><!-- Used to be btn-group -->

            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_registro_path(registro), :class => 'btn btn-default btn-xs' %>
            <!-- Temporarily hiding this button -->
            <!--<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        registro_path(registro),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-danger btn-xs' %> -->
            </div><!-- Btn group ends -->
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div><!-- End container for table -->

app/views/registros/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <!-- <Cell><Data ss:Type="String">ID</Data></Cell> -->
        <Cell><Data ss:Type="String">Nombre</Data></Cell>
        <Cell><Data ss:Type="String">Apellido</Data></Cell>
        <Cell><Data ss:Type="String">Puesto</Data></Cell>
        <Cell><Data ss:Type="String">Materia</Data></Cell>
        <Cell><Data ss:Type="String">Centro</Data></Cell>
        <Cell><Data ss:Type="String">Pueblo</Data></Cell>
        <Cell><Data ss:Type="String">Nivel</Data></Cell>
        <Cell><Data ss:Type="String">SEC</Data></Cell>
        <Cell><Data ss:Type="String">Email</Data></Cell>
        <Cell><Data ss:Type="String">Teléfono</Data></Cell>
        <Cell><Data ss:Type="String">Comentarios</Data></Cell>
      </Row>
    <% @registros.each do |registro| %>
      <Row>
        <!-- <Cell><Data ss:Type="Number"><%= registro.id %></Data></Cell> -->
        <Cell><Data ss:Type="String"><%= registro.nombre %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.apellido %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.puesto %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.materia %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.centro %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.pueblo %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.nivel %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.sec %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.email %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.telefono %></Data></Cell>
        <Cell><Data ss:Type="String"><%= registro.comentario %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/registros/new.html.erb
<%- model_class = Registro -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/registros/show.html.erb
<%- model_class = Registro -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @registro.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:apellido) %>:</strong></dt>
  <dd><%= @registro.apellido %></dd>
  <dt><strong><%= model_class.human_attribute_name(:puesto) %>:</strong></dt>
  <dd><%= @registro.puesto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:materia) %>:</strong></dt>
  <dd><%= @registro.materia %></dd>
  <dt><strong><%= model_class.human_attribute_name(:centro) %>:</strong></dt>
  <dd><%= @registro.centro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pueblo) %>:</strong></dt>
  <dd><%= @registro.pueblo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nivel) %>:</strong></dt>
  <dd><%= @registro.nivel %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sec) %>:</strong></dt>
  <dd><%= @registro.sec %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @registro.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @registro.telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comentario) %>:</strong></dt>
  <dd><%= @registro.comentario %></dd>
  <!-- <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @registro.user_id %></dd> -->
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              registros_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_registro_path(@registro), :class => 'btn btn-default' %>
<!-- Hiding this button -->
<!-- <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              registro_path(@registro),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %> -->

app/views/static_pages/index.html.erb
<div class="background-blur"></div>
<div class="container front">
	<div class="text-center front">
		<h1>Bienvenidos a <span class="fancy-font">SM<span class="fancy-black">ARTSIGNUP</span></span></h1>
		<h4>Herramienta para uso interno de SM Puerto Rico</h4>
		<%= link_to('Sign In', new_user_session_path, class: 'btn btn-default btn-lg', title: 'Sign In') %>
	</div><!-- col end -->
</div>